### ISSUE TITLE
Improve alerting engine

### ISSUE THREAD

**Issue by 0x0elliot** [thirdeye-dev/thirdeye#45]
For the time being, Alerting engine works on alerts like these:

```YAML
blockchain_alerts:
  - alert_type: "every_transaction"
    alerts:
      nameA:
        attribute: "{{ $transaction.gas }}"
        operator: ">="
        value: 100000
        webhook_url: "https://eot0jnzvvvbvr8j.m.pipedream.net/alerts"
        notifications:
          - send_email
          - send_sms
          - send_webhook
```

I want the alerts to have a more sophisticated conditioning logic. Like GitHub workflow IF statements. While making the prototype was fun, the UX here is weak. it's not apparent by default that {attribute operator value} is how the statement is evalutated. we need to make it so that files like these can be understood:

```YAML
blockchain_alerts:
  - alert_type: "every_transaction"
    alerts:
      nameA:
        condition: "txn_gasPrice  >= 100000 and txn_from  == '0xAb5801a7D398351b8bE11C439e05C5B3259aeC9B' "
        webhook_url: "https://eot0jnzvvvbvr8j.m.pipedream.net/alerts"
        notifications:
          - send_webhook
```
